-- Production-oriented Snowflake DDL.
-- The raw layer is deliberately permissive; quality rules are enforced after parsing.

CREATE OR REPLACE TABLE RAW_MEMBER_LANDING (
    RECORD_TYPE VARCHAR(1),
    MEMBER_NAME VARCHAR(255),
    MEMBER_ID VARCHAR(18),
    ENROLLMENT_DATE_RAW VARCHAR(50),
    LAST_FLIGHT_DATE_RAW VARCHAR(50),
    TIER_CODE VARCHAR(5),
    AGENT_NAME VARCHAR(255),
    STATE VARCHAR(5),
    COUNTRY VARCHAR(5),
    POST_CODE VARCHAR(20),
    DOB_RAW VARCHAR(50),
    IS_ACTIVE VARCHAR(1),
    SOURCE_FILE VARCHAR(255) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STG_MEMBER_PROFILES (
    MEMBER_KEY VARCHAR(50) NOT NULL,
    MEMBER_ID VARCHAR(18) NOT NULL,
    MEMBER_NAME VARCHAR(255) NOT NULL,
    ENROLLMENT_DATE DATE NOT NULL,
    FLIGHT_DATE DATE,
    TIER_CODE VARCHAR(5),
    AGENT_NAME VARCHAR(255),
    STATE VARCHAR(5),
    COUNTRY VARCHAR(5) NOT NULL,
    POST_CODE VARCHAR(20),
    DOB DATE,
    AGE NUMBER(3,0),
    STALE_MEMBER BOOLEAN,
    IS_ACTIVE VARCHAR(1),
    SOURCE_FILE VARCHAR(255) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL,
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE REJECTED_MEMBER_RECORDS (
    SOURCE_FILE VARCHAR(255),
    SOURCE_ROW_NUMBER NUMBER,
    MEMBER_ID VARCHAR(18),
    RAW_PAYLOAD VARIANT,
    REJECTION_REASON VARCHAR(1000),
    REJECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TABLE_USA LIKE STG_MEMBER_PROFILES;
CREATE OR REPLACE TABLE TABLE_IND LIKE STG_MEMBER_PROFILES;
CREATE OR REPLACE TABLE TABLE_AUS LIKE STG_MEMBER_PROFILES;

CREATE OR REPLACE TABLE RAW_REDEMPTION_JSON (
    SOURCE_FILE VARCHAR(255),
    PAYLOAD VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FCT_MEMBER_REDEMPTIONS (
    TXN_ID VARCHAR(50) NOT NULL,
    MEMBER_ID VARCHAR(18) NOT NULL,
    FEED_DATE DATE,
    TXN_DATE DATE,
    PARTNER VARCHAR(255),
    MILES_REDEEMED NUMBER(18,0),
    STATUS VARCHAR(20),
    SOURCE_FILE VARCHAR(255),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
