-- Mandatory field checks
SELECT * FROM STG_MEMBER_PROFILES
WHERE MEMBER_ID IS NULL
   OR MEMBER_NAME IS NULL
   OR ENROLLMENT_DATE IS NULL;

-- Key uniqueness after latest-record-wins
WITH MEMBERS AS (
    SELECT MEMBER_KEY FROM TABLE_USA
    UNION ALL SELECT MEMBER_KEY FROM TABLE_IND
    UNION ALL SELECT MEMBER_KEY FROM TABLE_AUS
)
SELECT MEMBER_KEY, COUNT(*) AS ROW_COUNT
FROM MEMBERS
GROUP BY MEMBER_KEY
HAVING COUNT(*) > 1;

-- Business/date checks
SELECT * FROM STG_MEMBER_PROFILES
WHERE (DOB IS NOT NULL AND DOB > CURRENT_DATE())
   OR (DOB IS NOT NULL AND ENROLLMENT_DATE < DOB)
   OR (FLIGHT_DATE IS NOT NULL AND FLIGHT_DATE < ENROLLMENT_DATE)
   OR AGE < 0 OR AGE > 115
   OR TIER_CODE NOT IN ('SLV', 'GLD', 'PLT')
   OR COUNTRY NOT IN ('USA', 'IND', 'AUS')
   OR IS_ACTIVE NOT IN ('A', 'I');

-- Redemption checks
SELECT * FROM FCT_MEMBER_REDEMPTIONS
WHERE TXN_ID IS NULL
   OR MEMBER_ID IS NULL
   OR TXN_DATE IS NULL
   OR MILES_REDEEMED < 0
   OR STATUS NOT IN ('COMPLETED', 'PENDING', 'CANCELLED', 'FAILED');

SELECT TXN_ID, COUNT(*) AS ROW_COUNT
FROM FCT_MEMBER_REDEMPTIONS
GROUP BY TXN_ID
HAVING COUNT(*) > 1;

-- Orphan redemption members
WITH MEMBERS AS (
    SELECT MEMBER_ID FROM TABLE_USA
    UNION SELECT MEMBER_ID FROM TABLE_IND
    UNION SELECT MEMBER_ID FROM TABLE_AUS
)
SELECT r.*
FROM FCT_MEMBER_REDEMPTIONS r
LEFT JOIN MEMBERS m ON r.MEMBER_ID = m.MEMBER_ID
WHERE m.MEMBER_ID IS NULL;

-- Reconciliation / observability checks
SELECT
    (SELECT COUNT(*) FROM RAW_MEMBER_LANDING) AS RAW_ROWS,
    (SELECT COUNT(*) FROM STG_MEMBER_PROFILES) AS VALID_STAGE_ROWS,
    (SELECT COUNT(*) FROM REJECTED_MEMBER_RECORDS) AS REJECTED_ROWS,
    (SELECT COUNT(*) FROM TABLE_USA)
      + (SELECT COUNT(*) FROM TABLE_IND)
      + (SELECT COUNT(*) FROM TABLE_AUS) AS CURRENT_TARGET_ROWS;
